### PR TITLE
Initial cleaning data

### PR DESCRIPTION
**Pull request by jemiar**
Jupyter notebook - clean yellow taxi 2016 January : trips from and to LGA

### CODE REVIEW

**Comment by seehamrun** [comment]
Do you have the csv that you pulled the data from? (or are you just accessing it via url?) sorry the diff is hard to read and I can't tell where the data is coming from...

**Comment by jemiar** [comment]
I downloaded the csv file from the nyc data portal for yellow taxi in Jan 2016.

**Comment by jemiar** [comment]
The original file s probably too big for commit. I'll output the processed data.

**Comment by seehamrun** [comment]
OK cool! Can you add the processed data to this commit? And also a comment somewhere in the jupyter notebook on where to get the OG data in case thats needed?

**Comment by jemiar** [comment]
I've added comments in the notebook and uploaded the 2 processed data files. Let me know if you have any questions.

**Comment by seehamrun** [comment]
Thanks Minh!

**Review by seehamrun — APPROVED** [review]

**Comment by seehamrun** [comment]
Feel free to merge but also qq: its not clear from the diff how you decided something was picked up or dropped off at LGA, could you include a quick tldr in the description of the PR ?

**Comment by jemiar** [comment]
I put comments along with the code in the notebook. I think it's easier to read that way.

**Pull request merged**
